name: PluginRPG
version: 1.0
author: AlexisZucher
main: fr.zucher.rpg.Main
commands:
  class:
    description: Choix classe
    permission: class.use
  menuclass:
    description: Menu classe
    permission: menuclass.use
  addHearts:
    description: Ajouter coeurs
    permission: addHearts.use
  resistance:
    description: bonus resistance
    permission: resistance.use
  getStuffIron:
    description: stuff fer
    permission: getStuffIron.use
  getStuffDiamond:
    description: stuff diamant
    permission: getStuffDiamond.use