name: PluginAmeliorationMinecraft
version: 2.0
author: Givrix
main: fr.givrix.pluginameliorationminecraft.PluginAmeliorationMinecraft
commands:
  pos:
    description: Affiche les coordonees d'un joueur
  follow:
    description: Donne une boussole qui pointe un joueur
  uhc:
    description: Passe le jeu en ultra hardcore
  inventory:
    description: Ouvre un inventaire commun accessible a tous les joueurs
  home:
    description: Defini un home ou s'y teleport